name: fake_store_api_package
description: "Dart/Flutter package to consume Fake Store API (products, carts, users, auth) with typed models and error handling."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6

flutter: null
